GET http://localhost:7071/api/job-start/gb4715 HTTP/1.1

###

GET http://localhost:7071/api/job-status/cb2a43bf-fcad-4eb0-a2bc-2dbb87c09ddc HTTP/1.1

###

GET http://localhost:7071/api/monitor-job/gb4715 HTTP/1.1